apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName }}
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  selector: {{ include "common.labels" . | nindent 4}}
  ports:
    - port: {{ .Values.port }}
      targetPort: {{ .Values.targetPort }}
      protocol: TCP
  type: LoadBalancer